config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'

  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
  <ul class="editTask">
    <%= form_with model: @task do |t| %>
      <li>
        <%= t.label :title %>
      </li>
      <li>
        <%= t.text_field :title %>
      </li>
      <li>
        <%= t.label :details %>
      </li>
      <li>
        <%= t.text_field :details %>
      </li>
      <li>
        <%= t.label :completed %>
        <%= t.check_box :completed %>
      </li>
      <li>
        <%= t.submit %>
      </li>
    <% end %>
  </ul>

app/views/tasks/edit.html.erb
<div class="container">

<h1>Edit TASK</h1>
<%= render "form" %>
</div>

app/views/tasks/index.html.erb
<div class="container">

  <h1>My tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
      <li>
        <%= link_to task.title, task_path(task) %>
        <%= link_to task_path(task), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?",
        } do %>
        <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </li>

    <% end %>
  </ul>
  <p class=tasks><%= link_to "Create new task", tasks_new_path %></p>
</div>

app/views/tasks/new.html.erb
<div class="container">

<h1>New TASK</h1>
<%= render "form" %>
</div>

app/views/tasks/show.html.erb
<div class="container">

  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <%= if @task.completed == true
        "This task is COMPLETED! Good job!!! "
      else
        "This task is NOT completed yet..."
      end
  %>

  <p><%= link_to "GO BACK", tasks_path %></p>
  <p><%= link_to "EDIT TASK", edit_task_path %></p>
</div>